// import.meta.env.BASE_URL isn't reliably slash-terminated: Astro only adds
// the trailing slash if the configured `base` already had one, and on
// Webflow Cloud the base is generated by their builder (from its own
// COSMIC_MOUNT_PATH env var) rather than our astro.config.mjs, so we can't
// control that. Strip any trailing slash here and always join with exactly
// one, so this works the same whether BASE_URL is "/", "/app", or "/app/".
export function withBase(path: string): string {
  const base = import.meta.env.BASE_URL.replace(/\/$/, "");
  return `${base}/${path.replace(/^\//, "")}`;
}
